### ISSUE TITLE
NTR FAO:0001030 aerial mycelium

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#11]
This term is being created for defining the GO term 'aerial mycelium formation'

[term]
id (will be) : ~FAO:0001030~ FAO:0001031
name:  'aerial mycelium'
def: a type of pre-sporulating mycelium that extends aerially, or perpendicular, to its substrate.
is_a:  FAO: 0000011 ! 'mycelium'

**Comment by mah11** [comment]
edited to reflect ID swap between this and #12

**Comment by mah11** [comment]
I've added this term, but I don't yet have things set up to be able to do a new FAO release. Can @cmungall step in for now?
