### ISSUE TITLE
NTR FAO:0001031 'substrate mycelium'

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#12]
This term is being created as the source of the logical definition of a new GO term, GO:0097738 'substrate mycelium formation.'

[term]
id (will be) : ~FAO:0001031~ FAO:0001030
name: 'substrate mycelium'
def: an invasive mycelium that forms within a solid or semi-solid substrate such as wood, soil or agar. [FAO:doi, FAO:pamgo, PMID: 3891055]
is_a: FAO:0000011 ! mycelium
is_a: FAO:0000001 ! fungal structure
xref: GO:0097738

**Comment by mah11** [comment]
edited to reflect ID swap between this and #11

**Comment by mah11** [comment]
I've added this term, but I don't yet have things set up to be able to do a new FAO release. Can @cmungall step in for now?

**Comment by cmungall** [comment]
making a release now
