### ISSUE TITLE
NTRs: perithecium & protoperithecium

### ISSUE THREAD

**Issue by cmungall** [obophenotype/fungal-anatomy-ontology#19]
For definitions, see: https://github.com/geneontology/go-ontology/issues/15616#issuecomment-394017091

**Comment by Achchuthan** [comment]
Hi @dianeoinglis,

I am currently working on making some phenotype annotations for fusarium species and looking for "Perithecium" in ontologies. I find perithecium in BRENDA BTO ontology. But, I am wondering whether these terms will be added to FAO?

Are there any plans for continuous development of FAO?

Thanks you so much for your help.

Best wishes,
Achchuthan

**Comment by mah11** [comment]
Hi @Achchuthan,

As Chris says in #18, I've agreed to take FAO on (and another PomBase curator @antonialock, will get involved as well in due course). I'll have to get up to speed with both the existing FAO content and the OSK-based release proceduce, so please bear with me.

In the meantime, I see that Chris has added the perithecium term. I can try using protoperithecium as a test; I hope to have time for it this week.

Midori

**Comment by mah11** [comment]
I've now put protoperithecium in pull request #25, with ID FAO:0002001.

Questions:
- @Achchuthan Should protoperithecium be a subtype (is_a) of fruitbody?
- @cmungall Who should merge the outstanding pull requests for this ticket?

Note to self: when PRs #23 & #25 merged, come back and add link perithecium develops_from protoperithecium.

**Comment by Achchuthan** [comment]
HI @mah11 
Thank you so much for your help with adding protoperithecium to FAO. Yes, both perithecium and protoperithecium should be a subtype of fruitbody.

Best wishes,
Achchuthan
