### ISSUE TITLE
Modify synonym for FAO:0000010 spore-bearing structure

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#2]
New GO term to add to FAO:

spore-bearing structure

https://github.com/geneontology/go-ontology/issues/12605

**Comment by tberardini** [comment]
Actually, you need to create the term first in FAO so that we can reference it when creating the new term (spore-bearing structure development) in the GO instead of the other way around. :)

**Comment by dianeoinglis** [comment]
Ok. I'll work on that, then will run it past @cmungall to be sure the final FAO.obo looks right.

**Comment by cmungall** [comment]
Hi @dianeoinglis - be sure to make your edits on fao-edit.obo - see the README-editors.md in the [src/ontology](https://github.com/obophenotype/fungal-anatomy-ontology/tree/master/src/ontology) directory

(doing it this way makes sense in the end, I promise!)

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis ,
Once you've added 'spore-bearing structure' in FAO, I'll create 'spore-bearing structure development' (https://github.com/geneontology/go-ontology/issues/12605). Commenting here so I get notified when you do. Thanks.

**Comment by dianeoinglis** [comment]
An existing term will  be a modified similar to the new GO term "spore-bearing structure formation." I have not actually edited the /src/FAO-edit.obo due to a software installation issue on my laptop that I'm trying to fix. I thought command line could also be used to edit the FAO-edit.obo file. I
https://github.com/geneontology/go-ontology/issues/12605#issuecomment-241804111

FAO:0000010
name: sporophore
def: "A structure directly within which spores are contained or from which spores are formed." [FAO:curators]
xref: GO:0075259
synonym: "spore-bearing organ" RELATED [] ADD:-synonym: "spore-bearing structure" RELATED [], ADD:-synonym: "spore-producing structure"
is_a: FAO:0000001 ! fungal structure

@tberardini

**Comment by dianeoinglis** [comment]
Details for modifying FAO: 0000010
Comment: 1) a fruiting body is typically a sexual structure. Does that make it a "narrow" synonym of sporophore or...?

Primary term name: 'sporophore'' (no change)
Update definition: "A multicellular spore-bearing anatomical structure that functions in the production of spores that are directly borne upon or within sporogenous cells that are part of the structure.'

Remove/obsolete synonym: 'spore-bearing organ'

Add exact synonym: 'spore-bearing structure'

Add exact synonym: 'spore-producing structure'

Add synonym: 'sporocarp'

Add synonym: 'fruiting body'
Add synonym: 'fruit body'
Add synonym: 'fruitbody'

Add synonym-types after determined.

Soliciting comments...thanks
