### ISSUE TITLE
assert is_a fungal structure

### ISSUE THREAD

**Issue by mah11** [obophenotype/fungal-anatomy-ontology#29]
There are about a dozen terms with no is_a parent either asserted or inferred (well, not much is inferred because FAO doesn't have logical defs yet). Looks like all can at least be is_a FAO:0000001 ! fungal structure.

**Comment by dianeoinglis** [comment]
I looked at the terms that lack an indicator of fungal structure and realized the majority are "multicellular structures" which is a term that has not yet been created. There are the children of 'fungal structure' terms, 'unicellular structure' and 'composite structure' I will request the multicellular term in another ticket.
Diane
