### ISSUE TITLE
NTR monkaryotic fruit body

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#3]
Fruitbody or fruiting body is the term used for the spore-bearing structure that are formed during sexual development following mating between two compatible mating-types, typically 'a' and 'alpha' strains. Cryptococcus and several other Basidiomycetes can self-mate (same-sex mating) under starvation conditions. As the nuclei are identical, this same-sex mating process is interchangeably referred to as haploid fruiting or monokaryotic fruiting. The process is similar to sexual fruiting however the resulting basidiospores are genetically identical.

I propose to add the term 'monokaryotic fruitbody' with the synonym 'haploid fruitbody.'

[term]
id (will be): FAO:0001023
name:  'monokaryotic fruit body'
Def:  "a specialized structure that produces or bears asexually derived spores from same-sex mating." [FAO:curators, FAO:doi]
synonym:  "monokaryotic fruiting body" EXACT [ ]
synonym:  "haploid fruiting body" EXACT [ ]
is_a:  FAO:0000001 ! fungal structure

Please review and comment on whether the information for this proposed term is accurate and acceptable.

Thanks,
Diane

@mah11
@tberardini

**Comment by dianeoinglis** [comment]
Updated details for editing FAO.obo

New ID: FAO:0001023
Use term name: 'monokaryotic fruiting body'

Use term definition: a spore-producing structure that is the result of same-sex (self) mating. These structures are produced by Cryptococcus species in a manner similar to sexual mating except that the resulting spores are isogenic with the parental strain.
 
Add is_a: ! FAO:0000001 'fungal structure'

**Add exact synonyms:**
'Monokaryotic fruit body'
'Monokaryotic fruit body'
'Haploid fruiting body'
'Haploid fruit body'
'Haploid fruitbody'

Question/comment: this term refers to a subset of sporophore/spore-bearing structures. Should a relationship to FAO:0000010 'sporophore' be included? It seems appropriate to use the highest parental term, is_a FAO: 00000001 'fungal' structure' but I'll follow the advise of a more experienced Ontology Editor.

**Comment by dianeoinglis** [comment]
Previously proposed FAO ID overlaps with last-assigned ID. Make the new term with FAO: 0001032

**Comment by dianeoinglis** [comment]
A minor change. Because the primary term name for FAO:0000007 uses the 'fruitbody' variation, create the term, ' monokaryotic fruitbody' for consistency. Make 'monokaryotic fruiting body' a synonym.

**Comment by pgaudet** [comment]
Hi @dianeoinglis 

How important is it that we assign IDs? It'd be easier (and safer I think) if we'd let Protégé do the assignment. 

Thanks, Pascale

**Comment by cmungall** [comment]
I agree

Whatever decision is made, make sure it's documented in the editors 
README:
https://github.com/obophenotype/fungal-anatomy-ontology/blob/master/src/ontology/README-editors.md

And make sure ID ranges are documented here:
https://github.com/obophenotype/fungal-anatomy-ontology/blob/master/src/ontology/fao-idranges.owl

**Comment by mah11** [comment]
id: FAO:0002006
name: monokaryotic fruitbody

For now I have asserted the more specific is_a sporophore link, because FAO does not yet have the logical definitions that would let a reasoner infer classifications. I also don't know what to put in a logical def for the "result of same-sex (self) mating" part of this particular text def.
