### ISSUE TITLE
NTR: multicellular fungal structure

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#33]
There is a term for unicellular structures and for composite (more than one organism) but the terms that Iack either term are the multicellular structures, such as sporophore, conidiophore, etc. As time permits, let's add this missing term.

NTR: 000xxxx multicellular structure, unicellular organism.
Def: a fungal structure composed of two or more cells of a single unicellular organism.
is_a FAO:0000001 fungal structure

NTR: 000xxxx multicellular structure, multicellular organism
Def: a fungal structure composed of two or more cells of a single multicellular organism.

**Comment by dianeoinglis** [comment]
FAO:0000004 ascocarp-bound ascus
FAO:0000006 stipe
FAO:0000007 fruitbody
FAO:0000008 ascocarp
FAO:0000009 pileus
FAO:0000010 sporophore *
FAO:0000011 mycelium
FAO:0000012 basidiocarp
FAO:0000014 ascus
FAO:0000015 free ascus
FAO:0000043 conidiophore
FAO:0000044 sterigma
FAO:0000047 cleistothecium
FAO:0000052 sporangium *
FAO:0000053 zygosporangium

**Comment by mah11** [comment]
FAO:0000061 fused clamp - query raised in #36
all others done
