### ISSUE TITLE
Invalid ISBN `ISBN:0879693798` in FAO

### ISSUE THREAD

**Issue by althonos** [obophenotype/fungal-anatomy-ontology#35]
Hi!

The `ISBN:0879693798` used as a cross-reference for the definition of [`FAO:0001023`](https://github.com/obophenotype/fungal-anatomy-ontology/blob/master/src/ontology/fao-edit.obo#L650) is invalid. If that helps, the closest valid one is `ISBN:0879693797` which links to [*Power of Bacterial Genetics: A Literature-Based Course*](https://www.abebooks.com/9780879693794/Power-Bacterial-Genetics-Literature-Based-Course-0879693797/plp) but I don't know if that the expected reference.

**Comment by mah11** [comment]
Thanks, @althonos - I think it's actually supposed to be ISBN:0879693568, though I've no idea how that got turned into the erroneous ID you found. Anyway, I'm correcting it now.
