### ISSUE TITLE
Travis build failure

### ISSUE THREAD

**Issue by mah11** [obophenotype/fungal-anatomy-ontology#38]
See #37 - I don't fully understand the report, but it doesn't look like something I can fix in the ontology. @cjm, any advice?

**Comment by mah11** [comment]
"ontology storage error"

**Comment by cmungall** [comment]
This is the issue:

```
[Term]
id: FAO:0001026
name: mycobiont
def: "OBSOLETE. The fungal component of the lichen partnership, absorbing nutrients and providing structural support for the plant." [BTO:0000892]
comment: This term was made obsolete because it represents a class of organism, not a fungal structure.
name: obsolete
```

I will fix and make the robot output more informative

**Comment by mah11** [comment]
oops! and thanks for output changes - I missed that because I got confused by the "ontology storage error" messaeg.
