### ISSUE TITLE
NTR conidiophore foot cell

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#4]
NTR for the first cell upon which a conidiophore develops.

id (will be): FAO:0001024
name: conidiophore foot cell
def:  "a specialized cell with an enlarged cell wall that develops in series of vegetative hyphae in a mycelium upon which a conidiophore develops."
develops_from: FAO:0001003 | hypha in mycelium
created_by: dinglis

Please review and comment on whether the information for this proposed term is accurate and acceptable.

@mah11
@tberardini

**Comment by dianeoinglis** [comment]
Updated details:

New def:  A specialized cell with an enlarged cell wall that develops from a hyphal cell in a septate mycelium and swells at the aerial terminus to form a conidiophore vesicle. The aerial portion of the foot cell forms the conidiophore stalk.

USE: develops_from: FAO:0001004 'septate hypha in mycelium' and NOT FAO:0001003.

**Comment by mah11** [comment]
id: FAO:0002007
name: conidiophore foot cell
