### ISSUE TITLE
Refer to FAO?

### ISSUE THREAD

**Issue by vtoure** [obophenotype/fungal-anatomy-ontology#41]
Hi, 

How would you advise to reference FAO in a manuscript? 
Also, the [homepage](https://www.yeastgenome.org/fungi/fungal_anatomy_ontology/index.html) link is broken in the README.

Thanks!

**Comment by ValWood** [comment]
I don't think there is a reference.

@mah11  now maintains, she may know more?

v

**Comment by mah11** [comment]
To the best of my knowledge, FAO has not been the subject of a dedicated peer-reviewed publication. In the absence of a paper, I think the best thing to do is follow the OBO Foundry policy as described under "Referring to an ontology" on this page:

http://obofoundry.org/docs/Citation.html

I'll change the broken link.
