### ISSUE TITLE
NTR: appressorium

### ISSUE THREAD

**Issue by Achchuthan** [obophenotype/fungal-anatomy-ontology#42]
Hi @mah11,
Can I request a new term for appressorium in FAO please? This term is present in BTO.

id: FAO:xxxxxxx
name: appressorium
def: "The flattened thickened tip of a hyphal branch by which some parasitic fungi are attached to their host."
is_a: FAO:0001001 ! hypha
xref: BTO:0000085

Thanks & best wishes,
Achchuthan

**Comment by mah11** [comment]
Note: the new term is committed but not yet in a release.

**Comment by Achchuthan** [comment]
Thanks a lot @mah11 for making this new term!!

**Comment by mah11** [comment]
I've just now got the release to work, too :)
