### ISSUE TITLE
Is FAO interested in a set of NCBITaxon x fruitbody terms?

### ISSUE THREAD

**Issue by ddooley** [obophenotype/fungal-anatomy-ontology#51]
In FoodOn we've needed to define common language references to mushrooms which include a "fruitbody and 'derives from' some [NCBITaxon]" axioms, e.g. [trumpet chanterelle](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_03414543).  Is FAO interested in housing/managing such terms? Here's our branch labelled [mushroom fruitbody](http://purl.obolibrary.org/obo/FOODON_00003528).  The subclasses could perhaps have the term "fruitbody" appended to them for clarity.

**Comment by ValWood** [comment]
Hello, sorry for the delayed response. I just realized I am responsible for this ontology.

I looked at your branch and although fruiting body would be in scope we would not add the instances (specific species) to FAO (i.e we would not create instances of fruitbody for each taxon (unless there was some specific sub-type of fruiting body that could be defined).

This seems like something that would be more appropriate to post-compose than to instantiate.

We have
id: FAO:0000007
name: fruitbody
def: "Any specialized structure which bears or contains sexually or asexually derived spores." [FAO:curators, SGD:clt]
synonym: "fruiting body" EXACT []

Let me know if there are any anatomy terms that you require. I am happy to add.

**Comment by ddooley** [comment]
Ok, I was just checking.  We'll precompose the entries in FoodOn.  Our need is to provide single identifiers for many food related databases, ultimately billions of references, so shying away from precomposition at this level!
Cheers,
Damion
