### ISSUE TITLE
NTR spherule

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#7]
(will be) id: FAO:0001027
name: spherule
def: "a large, round, thick-walled structure that contains endospores such as those produced by Coccidioides species within a host."
is_a: FAO:0000001 ! fungal structure
is_a: FAO:0000052 ! sporangium
created_by: dinglis

Please review and comment on whether the information for this proposed term is accurate and acceptable.

@mah11
@tberardini

**Comment by mah11** [comment]
id: FAO:0002009
name: spherule
