### ISSUE TITLE
NTR sexual structure

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#8]
# Grouping term

(will be) id:  FAO:0001029
name:  sexual structure
def:  "any structure that  develops during the mating process for the purpose of sexual reproduction."
is_a:  FAO:0000001 ! fungal structure
created_by: dinglis

@mah11
@tberardini

**Comment by mah11** [comment]
id: FAO:0002010
name: sexual structure
