### ISSUE TITLE
NTR mating filament

### ISSUE THREAD

**Issue by dianeoinglis** [obophenotype/fungal-anatomy-ontology#9]
To distinguish between other types of hyphae. 

(will be) id: FAO:0001028
name: mating filament
def: "the hypha that emerges from a yeast-form cell upon stimulation by the pheromone of a compatible mating partner."
is_a: FAO:0000001 ! fungal structure
created_by: dinglis

@mah11
@tberardini

**Comment by dianeoinglis** [comment]
Add to def: An example is observed in Cryptococcus species.

**Comment by mah11** [comment]
id: FAO:0002011
name: mating filament
